name: CI Pipeline

# ✅ Give the workflow permission to mint an OIDC token for Codecov
permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/custom-setup
      - run: npm run lint
      # optional auto-fix to reduce flaky fails
      - name: Prettier auto-fix
        run: npm run format:fix
      - name: Prettier check
        run: npm run format

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/custom-setup
      - run: npm test -- --coverage
      - name: Upload coverage to Codecov (OIDC)
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        # No token needed when OIDC is enabled by the permissions above

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      SITE_NAME: "Luxury Heaven – CI/CD Demo"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/custom-setup
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
