name: Dependency Check

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/custom-setup
      - run: npm audit --json > audit-report.json
      - name: Create issue if vulnerabilities found
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('audit-report.json', 'utf-8'));
            const total = report.metadata?.vulnerabilities?.total ?? 0;
            if (total > 0) {
              const body = [
                'Automated npm audit found vulnerabilities.',
                '',
                'Summary:',
                '```json',
                JSON.stringify(report.metadata?.vulnerabilities, null, 2),
                '```'
              ].join('\n');
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Security vulnerabilities found (${total})`,
                body
              });
            } else {
              core.info('No vulnerabilities found.');
            }
